# 🔢 Introduction to NumPy
## A Comprehensive Guide for BTech Students

---

**Course:** Python Programming | **Topic:** NumPy – Numerical Python | **Level:** Beginner to Intermediate

---

### 📚 Topics Covered:
1. NumPy Overview  
2. NumPy ndarray  
3. Datatypes in NumPy  
4. Array Creation  
5. List vs Array  
6. NumPy Attributes  
7. NumPy Operations  
8. NumPy Broadcasting  
9. NumPy Functions (String, Mathematical, Statistical, Sorting & Searching)  
10. NumPy Special Functions

> 💡 **Tip:** Run each cell using `Shift + Enter`. Try modifying examples to deepen your understanding!

---
## 📌 Section 1: NumPy Overview

**NumPy** (Numerical Python) is the foundational library for scientific computing in Python.

### Why NumPy?
| Feature | Python List | NumPy Array |
|--------|------------|-------------|
| Speed | Slow | Very Fast |
| Memory | More | Less |
| Operations | Element-by-element loop | Vectorized |
| Multidimensional | Complex | Built-in |
| Math functions | Limited | Extensive |

### Applications:
- 🔬 Scientific computing
- 📊 Data analysis & Machine Learning
- 🖼️ Image processing
- 🤖 Deep learning (tensors)
- 📡 Signal processing

In [ ]:
# Install NumPy (if not already installed)
# !pip install numpy

# Import NumPy — 'np' is the universal alias
import numpy as np

print("✅ NumPy imported successfully!")
print(f"📦 NumPy Version: {np.__version__}")

✅ NumPy imported successfully!
📦 NumPy Version: 2.0.2


---
## 📌 Section 2: NumPy ndarray (N-Dimensional Array)

The **ndarray** is the core data structure of NumPy. It is a grid of values, all of the **same type**, indexed by a tuple of non-negative integers.

- **1D Array** → Like a vector  
- **2D Array** → Like a matrix  
- **3D Array** → Like a cube of data

In [ ]:
# ── 1D Array ──
arr1d = np.array([10, 20, 30, 40, 50])
print("1D Array  :", arr1d)
print("Type      :", type(arr1d))
print("Dimensions:", arr1d.ndim)
print("Shape     :", arr1d.shape)

1D Array  : [10 20 30 40 50]
Type      : <class 'numpy.ndarray'>
Dimensions: 1
Shape     : (5,)


In [ ]:
arr = np.array([[[1,2,3],
               [4,5,6]],
                [[5,6,7],
                 [8,9,8]]])
print(type(arr))
print(arr.ndim)
print(arr.shape)

<class 'numpy.ndarray'>
3
(2, 2, 3)


In [ ]:
# ── 2D Array (Matrix) ──
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print("2D Array:\n", arr2d)
print("Dimensions:", arr2d.ndim)
print("Shape     :", arr2d.shape)

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensions: 2
Shape     : (3, 3)


In [ ]:
# ── 3D Array ──
arr3d = np.array([[[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]],
                  [[4, 5, 6],
                   [5, 6, 7],
                   [6, 7, 8]],
                  [[4, 5, 6],
                   [5, 6, 7],
                   [6, 7, 8]]
                  ])
print("3D Array:\n", arr3d)
print("Dimensions:", arr3d.ndim)
print("Shape     :", arr3d.shape)   # (depth, rows, cols)

3D Array:
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[4 5 6]
  [5 6 7]
  [6 7 8]]

 [[4 5 6]
  [5 6 7]
  [6 7 8]]]
Dimensions: 3
Shape     : (3, 3, 3)


---
## 📌 Section 3: Datatypes in NumPy

NumPy supports a wide range of numerical data types. All elements in an ndarray **must be of the same type**.

| Type Code | Description | Example |
|-----------|-------------|---------|
| `int8/16/32/64` | Signed integers | `-128` to `127` |
| `uint8/16/32/64` | Unsigned integers | `0` to `255` |
| `float16/32/64` | Floating-point | `3.14` |
| `complex64/128` | Complex numbers | `3+2j` |
| `bool` | Boolean | `True/False` |
| `str_` | String | `'hello'` |

In [ ]:
# Default dtype inference
a = np.array([1, 2, 3], dtype = np.float64)
b = np.array([1.5, 2.5, 3.5])
c = np.array([True, False, True])
d = np.array(['alpha', 'beta', 'gamma'])

print(f"Integer array : {a}  → dtype: {a.dtype}")
print(f"Float array   : {b}  → dtype: {b.dtype}")
print(f"Boolean array : {c}  → dtype: {c.dtype}")
print(f"String array  : {d}  → dtype: {d.dtype}")

Integer array : [1. 2. 3.]  → dtype: float64
Float array   : [1.5 2.5 3.5]  → dtype: float64
Boolean array : [ True False  True]  → dtype: bool
String array  : ['alpha' 'beta' 'gamma']  → dtype: <U5


In [ ]:
# Specifying dtype explicitly
e = np.array([1, 2, 3], dtype=np.float64)
f = np.array([1.9, 2.7, 3.3], dtype=np.int32)   # truncates decimals
g = np.array([0, 1, 0, 1], dtype=np.bool_)
h = np.array([1+2j, 3+4j], dtype=np.complex128)

print(f"Explicit float64 : {e}  → dtype: {e.dtype}")
print(f"Cast to int32    : {f}  → dtype: {f.dtype}")
print(f"Boolean          : {g}  → dtype: {g.dtype}")
print(f"Complex          : {h}  → dtype: {h.dtype}")

Explicit float64 : [1. 2. 3.]  → dtype: float64
Cast to int32    : [1 2 3]  → dtype: int32
Boolean          : [False  True False  True]  → dtype: bool
Complex          : [1.+2.j 3.+4.j]  → dtype: complex128


In [ ]:
# Type conversion using astype()
original  = np.array([1.8, 2.9, 3.1, 4.6])

converted = original.astype(np.int32)
rounded = np.round(original).astype(np.int32)


print(f"Original (float): {original}")
print(f"Converted (int) : {converted}")
print(f"Rounded (int)   : {rounded}")
print("Note: astype() truncates — it does NOT round!")


Original (float): [1.8 2.9 3.1 4.6]
Converted (int) : [1 2 3 4]
Rounded (int)   : [2. 3. 3. 5.]
Note: astype() truncates — it does NOT round!


---
## 📌 Section 4: Array Creation

NumPy provides many ways to create arrays beyond `np.array()`.

In [ ]:
# ── From Python sequences ──
from_list  = np.array([1, 2, 3, 4, 5])
from_tuple = np.array((10, 20, 30))
nested     = np.array([[1, 2], [3, 4], [5, 6]])   # 2D

print("From list  :", from_list)
print("From tuple :", from_tuple)
print("Nested (2D):\n", nested)

From list  : [1 2 3 4 5]
From tuple : [10 20 30]
Nested (2D):
 [[1 2]
 [3 4]
 [5 6]]


In [ ]:
# ── Special array creation functions ──
zeros   = np.zeros((3, 4))        # All zeros
ones    = np.ones((2, 3))         # All ones
full    = np.full((2, 2), 7)      # All sevens
eye     = np.eye(4)               # Identity matrix
empty_a = np.empty((2, 2))        # Uninitialized

print("zeros(3,4):\n", zeros)
print("\nones(2,3):\n", ones)
print("\nfull(2,2) with 7:\n", full)
print("\neye(4):\n", eye)
print("\nempty(2,2) — values are uninitialized:\n", empty_a)

zeros(3,4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

ones(2,3):
 [[1. 1. 1.]
 [1. 1. 1.]]

full(2,2) with 7:
 [[7 7]
 [7 7]]

eye(4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

empty(2,2) — values are uninitialized:
 [[1.8 2.9]
 [3.1 4.6]]


In [ ]:
# ── arange(start, stop, step) — like Python range() ──
r1 = np.arange(0, 10, 1)       # 0 to 9
r2 = np.arange(0, 20, 2)       # Even numbers
r3 = np.arange(10, 0, -1)      # Reverse
r4 = np.arange(0.0, 1.0, 0.2)  # Float step

print("arange(0,10,1)   :", r1)
print("arange(0,20,2)   :", r2)
print("arange(10,0,-1)  :", r3)
print("arange(0,1.0,0.2):", np.round(r4, 2))

arange(0,10,1)   : [0 1 2 3 4 5 6 7 8 9]
arange(0,20,2)   : [ 0  2  4  6  8 10 12 14 16 18]
arange(10,0,-1)  : [10  9  8  7  6  5  4  3  2  1]
arange(0,1.0,0.2): [0.  0.2 0.4 0.6 0.8]


In [ ]:
# ── linspace(start, stop, num) ──
# Returns 'num' evenly spaced values between start and stop (inclusive)
ls1 = np.linspace(0, 1, 5)          # 5 points from 0 to 1
ls2 = np.linspace(0, 100, 11)       # 11 points from 0 to 100
ls3 = np.linspace(0, 2*np.pi, 6)    # For trigonometry

print("linspace(0,1,5)   :", ls1)
print("linspace(0,100,11):", ls2)
print("linspace(0,2π,6)  :", np.round(ls3, 3))

print("\n🔑 Key difference:")
print("   arange   → you specify the STEP SIZE")
print("   linspace → you specify the NUMBER OF POINTS")

linspace(0,1,5)   : [0.   0.25 0.5  0.75 1.  ]
linspace(0,100,11): [  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
linspace(0,2π,6)  : [0.    1.257 2.513 3.77  5.027 6.283]

🔑 Key difference:
   arange   → you specify the STEP SIZE
   linspace → you specify the NUMBER OF POINTS


In [ ]:
# ── Random array creation ──
np.random.seed(42)   # For reproducibility

rand_uniform = np.random.random((3, 3))
rand_int     = np.random.randint(1, 100, (3, 3))
rand_normal  = np.random.randn(3, 3)
rand_choice  = np.random.choice([10, 20, 30, 40], size=5)

print("Random uniform (0–1):\n", np.round(rand_uniform, 3))
print("\nRandom integers (1–99):\n", rand_int)
print("\nRandom normal distribution:\n", np.round(rand_normal, 3))
print("\nRandom choice from list:", rand_choice)

Random uniform (0–1):
 [[0.45  0.395 0.927]
 [0.727 0.327 0.57 ]
 [0.521 0.961 0.845]]

Random integers (1–99):
 [[82 53 24]
 [26 89 60]
 [41 29 15]]

Random normal distribution:
 [[-1.876 -1.367  0.636]
 [-0.907  0.476  1.304]
 [ 0.212  0.597 -0.896]]

Random choice from list: [30 30 20 40 10]


---
## 📌 Section 5: List vs NumPy Array

Understanding the differences is critical for writing efficient Python code.

In [ ]:
import time

py_list = list(range(1_000_000))
np_arr  = np.arange(1_000_000)

# Speed comparison: multiply each element by 2
start = time.time()
list_result = [x * 2 for x in py_list]
list_time = time.time() - start

start = time.time()
arr_result = np_arr * 2
arr_time = time.time() - start

print(f"⏱️  Python List time : {list_time:.5f} sec")
print(f"⚡ NumPy Array time : {arr_time:.5f} sec")
print(f"🚀 NumPy is {list_time/arr_time:.1f}x faster!")

⏱️  Python List time : 0.05667 sec
⚡ NumPy Array time : 0.00495 sec
🚀 NumPy is 11.4x faster!


In [ ]:
# ── Arithmetic behavior differences ──
py_list = [1, 2, 3]
np_arr  = np.array([1, 2, 3])

print("List + List   :", py_list + [4, 5, 6])          # Concatenation!
print("Array + Array :", np_arr + np.array([4, 5, 6]))  # Element-wise

print("\nList * 3  :", py_list * 3)     # Repeats list!
print("Array * 3 :", np_arr * 3)        # Scales each element

print("\nList + 10 : ERROR (cannot add scalar to list directly)")
print("Array + 10:", np_arr + 10)       # Broadcasts scalar

List + List   : [1, 2, 3, 4, 5, 6]
Array + Array : [5 7 9]

List * 3  : [1, 2, 3, 1, 2, 3, 1, 2, 3]
Array * 3 : [3 6 9]

List + 10 : ERROR (cannot add scalar to list directly)
Array + 10: [11 12 13]


In [ ]:
import sys

# ── Memory comparison ──
n = 1_000_000
py_list = list(range(n))
np_arr  = np.arange(n, dtype=np.int64)

list_mem = sys.getsizeof(py_list) + sum(sys.getsizeof(x) for x in py_list)
arr_mem  = np_arr.nbytes

print(f"Python List memory : {list_mem:,} bytes  ({list_mem/(1024*1024):.1f} MB)")
print(f"NumPy Array memory : {arr_mem:,} bytes  ({arr_mem/(1024*1024):.1f} MB)")
print(f"💾 NumPy uses {list_mem/arr_mem:.1f}x LESS memory!")

Python List memory : 36,000,056 bytes  (34.3 MB)
NumPy Array memory : 8,000,000 bytes  (7.6 MB)
💾 NumPy uses 4.5x LESS memory!


In [ ]:
# ── Indexing & Slicing ──
np_arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print("Array             :", np_arr)
print("Index [2]         :", np_arr[2])
print("Slice [2:6]       :", np_arr[2:6])
print("Every other [::2] :", np_arr[::2])
print("Reverse  [::-1]   :", np_arr[::-1])
print("Last 3   [-3:]    :", np_arr[-3:])

# 2D Indexing
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Matrix:\n", mat)
print("mat[1,2]    :", mat[1,2])
print("mat[0,:]    :", mat[0,:])       # Entire row 0
print("mat[:,1]    :", mat[:,1])       # Entire column 1
print("mat[0:2,1:3]:\n", mat[0:2, 1:3])

Array             : [ 10  20  30  40  50  60  70  80  90 100]
Index [2]         : 30
Slice [2:6]       : [30 40 50 60]
Every other [::2] : [10 30 50 70 90]
Reverse  [::-1]   : [100  90  80  70  60  50  40  30  20  10]
Last 3   [-3:]    : [ 80  90 100]

2D Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
mat[1,2]    : 6
mat[0,:]    : [1 2 3]
mat[:,1]    : [2 5 8]
mat[0:2,1:3]:
 [[2 3]
 [5 6]]


---
## 📌 Section 6: NumPy Array Attributes

Every ndarray has built-in **attributes** (properties) that give information about the array.

In [ ]:
arr = np.array([[1.0, 2.0, 3.0, 4.0],
                [5.0, 6.0, 7.0, 8.0],
                [9.0, 10.0, 11.0, 12.0]])

print("Array:\n", arr)
print("-" * 45)
print(f"ndim     : {arr.ndim}       — number of dimensions")
print(f"shape    : {arr.shape}    — rows × columns")
print(f"size     : {arr.size}       — total elements")
print(f"dtype    : {arr.dtype}  — data type")
print(f"itemsize : {arr.itemsize}        — bytes per element")
print(f"nbytes   : {arr.nbytes}       — total bytes (size × itemsize)")
print(f"T (Transpose):\n{arr.T}")

Array:
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
---------------------------------------------
ndim     : 2       — number of dimensions
shape    : (3, 4)    — rows × columns
size     : 12       — total elements
dtype    : float64  — data type
itemsize : 8        — bytes per element
nbytes   : 96       — total bytes (size × itemsize)
T (Transpose):
[[ 1.  5.  9.]
 [ 2.  6. 10.]
 [ 3.  7. 11.]
 [ 4.  8. 12.]]


---
## 📌 Section 7: NumPy Operations

### 7.1 Arithmetic Operations
NumPy operations are **element-wise** by default.

In [ ]:
a = np.array([10, 20, 30, 40])
b = np.array([1,  2,  3,  4])

print(f"a         = {a}")
print(f"b         = {b}")
print("-" * 40)
print(f"a + b     = {a + b}")
print(f"a - b     = {a - b}")
print(f"a * b     = {a * b}")
print(f"a / b     = {a / b}")
print(f"a // b    = {a // b}   (floor division)")
print(f"a % b     = {a % b}    (modulo)")
print(f"a ** 2    = {a ** 2}   (power)")
print(f"sqrt(a)   = {np.sqrt(a)}")

a         = [10 20 30 40]
b         = [1 2 3 4]
----------------------------------------
a + b     = [11 22 33 44]
a - b     = [ 9 18 27 36]
a * b     = [ 10  40  90 160]
a / b     = [10. 10. 10. 10.]
a // b    = [10 10 10 10]   (floor division)
a % b     = [0 0 0 0]    (modulo)
a ** 2    = [ 100  400  900 1600]   (power)
sqrt(a)   = [3.16227766 4.47213595 5.47722558 6.32455532]


In [ ]:
# ── Comparison & Boolean Indexing ──
arr = np.array([15, 3, 22, 8, 19, 7])

print("Array        :", arr)
print("arr > 10     :", arr > 10)
print("arr == 8     :", arr == 8)
print("arr[arr>10]  :", arr[arr > 10])   # Boolean indexing

mask = (arr > 5) & (arr < 20)
print("5 < arr < 20 :", arr[mask])

Array        : [15  3 22  8 19  7]
arr > 10     : [ True False  True False  True False]
arr == 8     : [False False False  True False False]
arr[arr>10]  : [15 22 19]
5 < arr < 20 : [15  8 19  7]


In [ ]:
# ── Matrix Operations ──
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("A:\n", A)
print("B:\n", B)
print("\nA * B (element-wise):\n", A * B)
print("\nA @ B (matrix multiply):\n", A @ B)
print("\nnp.dot(A,B):\n", np.dot(A, B))
print("\nTranspose A.T:\n", A.T)
print("\nnp.linalg.det(A):", np.linalg.det(A))
print("\nnp.linalg.inv(A):\n", np.linalg.inv(A))

A:
 [[1 2]
 [3 4]]
B:
 [[5 6]
 [7 8]]

A * B (element-wise):
 [[ 5 12]
 [21 32]]

A @ B (matrix multiply):
 [[19 22]
 [43 50]]

np.dot(A,B):
 [[19 22]
 [43 50]]

Transpose A.T:
 [[1 3]
 [2 4]]

np.linalg.det(A): -2.0000000000000004

np.linalg.inv(A):
 [[-2.   1. ]
 [ 1.5 -0.5]]


---
## 📌 Section 8: NumPy Broadcasting

**Broadcasting** is NumPy's mechanism to perform operations on arrays with **different shapes**.

### Broadcasting Rules:
1. If arrays have different `ndim`, the smaller array is padded with `1`s on the **left**.
2. Dimensions of size `1` are **stretched** to match the other array.
3. If sizes still don't match → **error**.

```
Shape (3,4) + Shape (4,)   → OK!  (4 is broadcast across rows)
Shape (3,4) + Shape (3,1)  → OK!  (3,1 → 3,4)
Shape (3,4) + Shape (3,)   → ERROR
```

In [ ]:
# ── Scalar Broadcasting ──
arr = np.array([1, 2, 3, 4, 5])
print("arr       :", arr)
print("arr + 100 :", arr + 100)   # 100 broadcast to all elements
print("arr * 2   :", arr * 2)
print("arr ** 2  :", arr ** 2)

arr       : [1 2 3 4 5]
arr + 100 : [101 102 103 104 105]
arr * 2   : [ 2  4  6  8 10]
arr ** 2  : [ 1  4  9 16 25]


In [ ]:
# ── 2D + 1D Broadcasting ──
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
row = np.array([10, 20, 30])         # Shape (3,)
col = np.array([[10], [20], [30]])   # Shape (3,1)

print("Matrix (3×3):\n", matrix)
print("\nRow vector + Matrix:\n", matrix + row)
print("\nColumn vector + Matrix:\n", matrix + col)

Matrix (3×3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Row vector + Matrix:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]

Column vector + Matrix:
 [[11 12 13]
 [24 25 26]
 [37 38 39]]


In [ ]:
# ── Practical: Normalize student marks ──
marks = np.array([[85, 78, 92],
                  [72, 88, 65],
                  [90, 95, 80]])

col_max = marks.max(axis=0)
col_min = marks.min(axis=0)

normalized = (marks - col_min) / (col_max - col_min) * 100

print("Original Marks:\n", marks)
print("\nColumn Max (per subject):", col_max)
print("Column Min (per subject):", col_min)
print("\nNormalized (0–100):\n", np.round(normalized, 1))

Original Marks:
 [[85 78 92]
 [72 88 65]
 [90 95 80]]

Column Max (per subject): [90 95 92]
Column Min (per subject): [72 78 65]

Normalized (0–100):
 [[ 72.2   0.  100. ]
 [  0.   58.8   0. ]
 [100.  100.   55.6]]


---
## 📌 Section 9: NumPy Functions

### 9.1 String Functions (`numpy.char`)
NumPy provides vectorized string operations via `np.char`.

In [ ]:
names    = np.array(['alice', 'bob', 'charlie', 'diana'])
subjects = np.array(['  Math  ', '  Physics  ', '  Chemistry  '])
greet    = np.array(['Hello', 'World', 'NumPy'])

print("Original         :", names)
print("upper()          :", np.char.upper(names))
print("title()          :", np.char.title(names))
print("capitalize()     :", np.char.capitalize(names))
print("strip()          :", np.char.strip(subjects))
print("add() (concat)   :", np.char.add(greet, ['!', ' Python', ' 3']))
print("str_len()        :", np.char.str_len(names))
print("replace a → @    :", np.char.replace(names, 'a', '@'))
print("startswith 'a'   :", np.char.startswith(names, 'a'))
print("find 'i'         :", np.char.find(names, 'i'))

Original         : ['alice' 'bob' 'charlie' 'diana']
upper()          : ['ALICE' 'BOB' 'CHARLIE' 'DIANA']
title()          : ['Alice' 'Bob' 'Charlie' 'Diana']
capitalize()     : ['Alice' 'Bob' 'Charlie' 'Diana']
strip()          : ['Math' 'Physics' 'Chemistry']
add() (concat)   : ['Hello!' 'World Python' 'NumPy 3']
str_len()        : [5 3 7 5]
replace a → @    : ['@lice' 'bob' 'ch@rlie' 'di@n@']
startswith 'a'   : [ True False False False]
find 'i'         : [ 2 -1  5  1]


### 9.2 Mathematical Functions

In [ ]:
x     = np.array([0, 30, 45, 60, 90])
x_rad = np.radians(x)

print("=== Trigonometric Functions ===")
print(f"Degrees : {x}")
print(f"sin     : {np.round(np.sin(x_rad), 4)}")
print(f"cos     : {np.round(np.cos(x_rad), 4)}")
print(f"tan     : {np.round(np.tan(x_rad), 4)}")

y = np.array([1, 2, 4, 8, 16])
print("\n=== Logarithmic & Exponential ===")
print(f"Array   : {y}")
print(f"log(y)  : {np.round(np.log(y), 3)}")
print(f"log2(y) : {np.round(np.log2(y), 3)}")
print(f"log10(y): {np.round(np.log10(y), 3)}")
print(f"exp([0,1,2,3]): {np.round(np.exp([0,1,2,3]), 3)}")

z = np.array([-5, -1, 0, 1, 4, 9])
print("\n=== Rounding & Absolute ===")
print(f"abs(z)  : {np.abs(z)}")
print(f"sqrt    : {np.sqrt(np.abs(z))}")
print(f"floor   : {np.floor([1.2, 2.7, -1.5])}")
print(f"ceil    : {np.ceil([1.2, 2.7, -1.5])}")
print(f"round   : {np.round([1.245, 2.756, -1.5], 1)}")

=== Trigonometric Functions ===
Degrees : [ 0 30 45 60 90]
sin     : [0.     0.5    0.7071 0.866  1.    ]
cos     : [1.     0.866  0.7071 0.5    0.    ]
tan     : [0.00000000e+00 5.77400000e-01 1.00000000e+00 1.73210000e+00
 1.63312394e+16]

=== Logarithmic & Exponential ===
Array   : [ 1  2  4  8 16]
log(y)  : [0.    0.693 1.386 2.079 2.773]
log2(y) : [0. 1. 2. 3. 4.]
log10(y): [0.    0.301 0.602 0.903 1.204]
exp([0,1,2,3]): [ 1.     2.718  7.389 20.086]

=== Rounding & Absolute ===
abs(z)  : [5 1 0 1 4 9]
sqrt    : [2.23606798 1.         0.         1.         2.         3.        ]
floor   : [ 1.  2. -2.]
ceil    : [ 2.  3. -1.]
round   : [ 1.2  2.8 -1.5]


### 9.3 Statistical Functions

In [ ]:
# Marks of 5 students in 4 subjects
marks = np.array([[85, 78, 92, 88],
                  [72, 88, 65, 79],
                  [90, 95, 80, 87],
                  [60, 55, 70, 65],
                  [95, 82, 88, 91]])

print("Marks Matrix (5 students × 4 subjects):\n", marks)
print("-" * 50)
print(f"Overall Mean      : {np.mean(marks):.2f}")
print(f"Overall Median    : {np.median(marks):.2f}")
print(f"Overall Std Dev   : {np.std(marks):.2f}")
print(f"Overall Variance  : {np.var(marks):.2f}")
print(f"Min / Max         : {np.min(marks)} / {np.max(marks)}")
print()
print(f"Mean per student  : {np.mean(marks, axis=1)}")
print(f"Mean per subject  : {np.mean(marks, axis=0)}")
print(f"Sum per student   : {np.sum(marks, axis=1)}")
print()
print(f"25th percentile   : {np.percentile(marks, 25)}")
print(f"50th percentile   : {np.percentile(marks, 50)}")
print(f"75th percentile   : {np.percentile(marks, 75)}")

Marks Matrix (5 students × 4 subjects):
 [[85 78 92 88]
 [72 88 65 79]
 [90 95 80 87]
 [60 55 70 65]
 [95 82 88 91]]
--------------------------------------------------
Overall Mean      : 80.25
Overall Median    : 83.50
Overall Std Dev   : 11.68
Overall Variance  : 136.39
Min / Max         : 55 / 95

Mean per student  : [85.75 76.   88.   62.5  89.  ]
Mean per subject  : [80.4 79.6 79.  82. ]
Sum per student   : [343 304 352 250 356]

25th percentile   : 71.5
50th percentile   : 83.5
75th percentile   : 88.5


### 9.4 Sorting and Searching Functions

In [ ]:
# ── Sorting ──
arr = np.array([64, 25, 12, 22, 11, 90, 45])
print("Original  :", arr)
print("Sorted    :", np.sort(arr))
print("Descending:", np.sort(arr)[::-1])
print("argsort() :", np.argsort(arr))   # Indices that would sort

mat = np.array([[3, 1, 2], [9, 6, 7], [4, 8, 5]])
print("\n2D Matrix:\n", mat)
print("Sort along axis=0 (columns):\n", np.sort(mat, axis=0))
print("Sort along axis=1 (rows)   :\n", np.sort(mat, axis=1))

Original  : [64 25 12 22 11 90 45]
Sorted    : [11 12 22 25 45 64 90]
Descending: [90 64 45 25 22 12 11]
argsort() : [4 2 3 1 6 0 5]

2D Matrix:
 [[3 1 2]
 [9 6 7]
 [4 8 5]]
Sort along axis=0 (columns):
 [[3 1 2]
 [4 6 5]
 [9 8 7]]
Sort along axis=1 (rows)   :
 [[1 2 3]
 [6 7 9]
 [4 5 8]]


In [ ]:
# ── Searching ──
arr = np.array([15, 3, 22, 8, 19, 7, 22, 11])
print("Array:", arr)

print("\nargmax()           :", np.argmax(arr), "→ value:", arr[np.argmax(arr)])
print("argmin()           :", np.argmin(arr), "→ value:", arr[np.argmin(arr)])

indices = np.where(arr > 10)
print("\nwhere(arr>10)      :", indices[0], "→ values:", arr[indices])

result = np.where(arr > 10, arr, 0)
print("where(>10, arr, 0) :", result)

sorted_arr = np.sort(arr)
print("\nSorted:", sorted_arr)
print("searchsorted(12)   :", np.searchsorted(sorted_arr, 12))

a = np.array([0, 5, 0, 3, 0, 8])
print("\nnonzero([0,5,0,3,0,8]):", np.nonzero(a)[0])

Array: [15  3 22  8 19  7 22 11]

argmax()           : 2 → value: 22
argmin()           : 1 → value: 3

where(arr>10)      : [0 2 4 6 7] → values: [15 22 19 22 11]
where(>10, arr, 0) : [15  0 22  0 19  0 22 11]

Sorted: [ 3  7  8 11 15 19 22 22]
searchsorted(12)   : 4

nonzero([0,5,0,3,0,8]): [1 3 5]


---
## 📌 Section 10: NumPy Special Functions

In [ ]:
# ── reshape() ──
arr = np.arange(1, 25)   # 24 elements
print("Original (24 elements):", arr)

r1 = arr.reshape(4, 6)
r2 = arr.reshape(2, 3, 4)
r3 = arr.reshape(6, -1)   # -1: NumPy calculates automatically

print("\nreshape(4,6):\n", r1)
print("\nreshape(2,3,4):\n", r2)
print("\nreshape(6,-1):\n", r3)
print("\nflatten():", r1.flatten())
print("ravel()  :", r1.ravel())

Original (24 elements): [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

reshape(4,6):
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

reshape(2,3,4):
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

reshape(6,-1):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
ravel()  : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [ ]:
# ── sum() ──
arr2d = np.array([[1,  2,  3,  4],
                  [5,  6,  7,  8],
                  [9, 10, 11, 12]])

print("Matrix:\n", arr2d)
print("\nsum() total        :", np.sum(arr2d))
print("sum(axis=0) cols   :", np.sum(arr2d, axis=0))
print("sum(axis=1) rows   :", np.sum(arr2d, axis=1))
print("cumsum()           :", np.cumsum(arr2d))
print("prod([1..5])       :", np.prod([1, 2, 3, 4, 5]))

Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

sum() total        : 78
sum(axis=0) cols   : [15 18 21 24]
sum(axis=1) rows   : [10 26 42]
cumsum()           : [ 1  3  6 10 15 21 28 36 45 55 66 78]
prod([1..5])       : 120


In [ ]:
# ── random() ──
np.random.seed(0)

print("random()          :", np.random.random())
print("random(5)         :", np.round(np.random.random(5), 3))
print("random((2,3))     :\n", np.round(np.random.random((2,3)), 3))
print("randint(1,100,5)  :", np.random.randint(1, 100, 5))
print("randn(5)          :", np.round(np.random.randn(5), 3))
print("uniform(0,10,5)   :", np.round(np.random.uniform(0, 10, 5), 2))

arr = np.arange(10)
np.random.shuffle(arr)
print("shuffle arange(10):", arr)
print("choice(arr,5)     :", np.random.choice(arr, 5, replace=False))

random()          : 0.5488135039273248
random(5)         : [0.715 0.603 0.545 0.424 0.646]
random((2,3))     :
 [[0.438 0.892 0.964]
 [0.383 0.792 0.529]]
randint(1,100,5)  : [89 82 38 26 78]
randn(5)          : [ 1.221 -1.339  0.428 -0.123  1.414]
uniform(0,10,5)   : [5.2  6.79 7.21 5.82 5.37]
shuffle arange(10): [1 8 9 5 2 6 3 7 4 0]
choice(arr,5)     : [5 9 8 7 4]


In [ ]:
# ── zeros() and ones() ──
print("zeros(5)         :", np.zeros(5))
print("zeros(3,4):\n",      np.zeros((3, 4)))
print("zeros(2,3) int:\n",  np.zeros((2, 3), dtype=np.int32))
print("ones(5)          :", np.ones(5))
print("ones(3,3):\n",       np.ones((3, 3)))

# ML use-case: weight initialisation
weights = np.zeros((4, 3))
bias    = np.ones((1, 3))
print("\nML weight matrix (4×3):\n", weights)
print("ML bias vector (1×3)  :\n", bias)

zeros(5)         : [0. 0. 0. 0. 0.]
zeros(3,4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
zeros(2,3) int:
 [[0 0 0]
 [0 0 0]]
ones(5)          : [1. 1. 1. 1. 1.]
ones(3,3):
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

ML weight matrix (4×3):
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ML bias vector (1×3)  :
 [[1. 1. 1.]]


In [ ]:
# ── mean() ──
scores = np.array([[85, 78, 92],
                   [72, 88, 65],
                   [90, 95, 80]])

print("Scores:\n", scores)
print(f"\nOverall mean           : {np.mean(scores):.2f}")
print(f"Row means (per student): {np.mean(scores, axis=1)}")
print(f"Col means (per subject): {np.mean(scores, axis=0)}")

data    = np.array([70, 85, 90])
weights = np.array([0.3, 0.3, 0.4])
print(f"\nWeighted mean {data} × {weights}: {np.average(data, weights=weights)}")

Scores:
 [[85 78 92]
 [72 88 65]
 [90 95 80]]

Overall mean           : 82.78
Row means (per student): [85.         75.         88.33333333]
Col means (per subject): [82.33333333 87.         79.        ]

Weighted mean [70 85 90] × [0.3 0.3 0.4]: 82.5


In [ ]:
# ── dot() ──
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print(f"v1 = {v1},  v2 = {v2}")
print(f"dot(v1,v2) = {np.dot(v1, v2)}  (1×4 + 2×5 + 3×6 = {1*4+2*5+3*6})")

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
print(f"\nA (2×3):\n{A}")
print(f"B (3×2):\n{B}")
print(f"A @ B  (2×2):\n{np.dot(A, B)}")

X = np.array([[1, 0.5], [2, 1.5], [3, 2.5]])
W = np.array([0.4, 0.6])
b = 1.0
print(f"\n🤖 ML: X@W+b = {np.dot(X, W) + b}")

v1 = [1 2 3],  v2 = [4 5 6]
dot(v1,v2) = 32  (1×4 + 2×5 + 3×6 = 32)

A (2×3):
[[1 2 3]
 [4 5 6]]
B (3×2):
[[ 7  8]
 [ 9 10]
 [11 12]]
A @ B  (2×2):
[[ 58  64]
 [139 154]]

🤖 ML: X@W+b = [1.7 2.7 3.7]


In [ ]:
# ── std() — Standard Deviation ──
class_a = np.array([85, 86, 84, 85, 84, 86])  # Consistent
class_b = np.array([60, 95, 50, 99, 55, 91])  # Spread

print(f"Class A scores : {class_a}")
print(f"Class A mean   : {np.mean(class_a):.2f}")
print(f"Class A std    : {np.std(class_a):.2f}  ← Low variance")

print(f"\nClass B scores : {class_b}")
print(f"Class B mean   : {np.mean(class_b):.2f}")
print(f"Class B std    : {np.std(class_b):.2f}  ← High variance")

print(f"\nSample std (ddof=1): {np.std(class_b, ddof=1):.2f}")
print(f"Variance            : {np.var(class_b):.2f}")

Class A scores : [85 86 84 85 84 86]
Class A mean   : 85.00
Class A std    : 0.82  ← Low variance

Class B scores : [60 95 50 99 55 91]
Class B mean   : 75.00
Class B std    : 20.34  ← High variance

Sample std (ddof=1): 22.28
Variance            : 413.67


In [ ]:
# ── empty() ──
e1 = np.empty(5)
e2 = np.empty((3, 3))

print("empty(5)   :", e1)
print("empty(3,3):\n", e2)
print("\n⚠️  WARNING: empty() does NOT guarantee zeros!")
print("   Use only when you WILL fill every element before reading.")

result = np.empty(10)
for i in range(10):
    result[i] = i ** 2
print("\nPre-allocated & filled:", result)

empty(5)   : [1. 1. 1. 1. 1.]
empty(3,3):
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

⚠️  WARNING: empty() does NOT guarantee zeros!
   Use only when you WILL fill every element before reading.

Pre-allocated & filled: [ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]


In [ ]:
# ── arange() ──
print("arange(5)           :", np.arange(5))
print("arange(2,10)        :", np.arange(2, 10))
print("arange(0,10,2)      :", np.arange(0, 10, 2))
print("arange(10,0,-1)     :", np.arange(10, 0, -1))
print("arange(0.0,1.0,0.2) :", np.round(np.arange(0.0, 1.0, 0.2), 2))

matrix = np.arange(1, 10).reshape(3, 3)
print("\narange(1,10).reshape(3,3):\n", matrix)

arange(5)           : [0 1 2 3 4]
arange(2,10)        : [2 3 4 5 6 7 8 9]
arange(0,10,2)      : [0 2 4 6 8]
arange(10,0,-1)     : [10  9  8  7  6  5  4  3  2  1]
arange(0.0,1.0,0.2) : [0.  0.2 0.4 0.6 0.8]

arange(1,10).reshape(3,3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# ── linspace() ──
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

print("linspace(0,1,5)              :", np.linspace(0, 1, 5))
print("linspace(0,10,6)             :", np.linspace(0, 10, 6))
print("linspace(0,1,5,endpoint=False):", np.linspace(0, 1, 5, endpoint=False))

# Plot sine and cosine
x     = np.linspace(0, 2 * np.pi, 300)
y_sin = np.sin(x)
y_cos = np.cos(x)

fig, ax = plt.subplots(figsize=(8, 3))
ax.plot(x, y_sin, label='sin(x)', color='royalblue', linewidth=2)
ax.plot(x, y_cos, label='cos(x)', color='tomato',    linewidth=2, linestyle='--')
ax.set_title("Sine and Cosine using np.linspace()", fontsize=13)
ax.set_xlabel("x (radians)")
ax.set_ylabel("Amplitude")
ax.legend()
ax.grid(True, alpha=0.4)
plt.tight_layout()
plt.savefig("sine_cosine_wave.png", dpi=100, bbox_inches='tight')
plt.show()
print("\n✅ Plot saved as 'sine_cosine_wave.png'")

linspace(0,1,5)              : [0.   0.25 0.5  0.75 1.  ]
linspace(0,10,6)             : [ 0.  2.  4.  6.  8. 10.]
linspace(0,1,5,endpoint=False): [0.  0.2 0.4 0.6 0.8]

✅ Plot saved as 'sine_cosine_wave.png'


---
## 🏋️ Practice Exercises

> ✏️ Try solving these on your own before looking at the solutions!

---

### Exercise 1: Array Creation & Attributes

Create the following arrays and print their `shape`, `dtype`, `ndim`, and `size`:
- A 1D array of the first 10 odd numbers
- A 3×3 identity matrix
- A 4×5 matrix of random integers between 50 and 100

Write your solution above ↑
--------------------------------------------------


---
### Exercise 2: Array Operations & Indexing

Given this matrix:
```
[[10,  20,  30,  40],
 [50,  60,  70,  80],
 [90, 100, 110, 120]]
```
- Extract the 2nd row
- Extract the last column
- Extract sub-matrix rows 0–1, cols 1–2
- Find all elements greater than 65
- Replace all elements less than 50 with 0

In [ ]:
# ✏️ Your solution here
mat = np.array([[ 10,  20,  30,  40],
                [ 50,  60,  70,  80],
                [ 90, 100, 110, 120]])

# Your code here...

print("Write your solution above ↑")
print("-" * 50)

# 💡 SOLUTION:
# print("2nd row         :", mat[1, :])
# print("Last column     :", mat[:, -1])
# print("Sub-matrix      :\n", mat[0:2, 1:3])
# print(">65             :", mat[mat > 65])
# mat_copy = mat.copy()
# mat_copy[mat_copy < 50] = 0
# print("Zeros below 50  :\n", mat_copy)

Write your solution above ↑
--------------------------------------------------


---
### Exercise 3: Broadcasting

Scores of 4 students in 3 subjects:
```
[[80, 70, 90],
 [65, 75, 85],
 [55, 60, 70],
 [95, 88, 92]]
```
- Add grace marks `[5, 10, 3]` to each row using broadcasting
- Calculate percentage if max marks per subject is `[100, 80, 100]`
- Apply a scaling factor of `1.05` to all scores

In [ ]:
# ✏️ Your solution here
scores = np.array([[80, 70, 90],
                   [65, 75, 85],
                   [55, 60, 70],
                   [95, 88, 92]])

# Your code here...

print("Write your solution above ↑")
print("-" * 50)

# 💡 SOLUTION:
# grace = np.array([5, 10, 3])
# print("After grace marks:\n", scores + grace)
#
# max_marks = np.array([100, 80, 100])
# percentage = (scores / max_marks) * 100
# print("Percentages:\n", np.round(percentage, 1))
#
# print("Scaled (×1.05):\n", np.round(scores * 1.05, 1))

Write your solution above ↑
--------------------------------------------------


---
### Exercise 4: Special Functions

Using NumPy special functions:
1. Create a 3×4 array using `arange` + `reshape`. Find mean, std, min, max.
2. Generate 100 points between 0 and π using `linspace`, compute `sin`, find index & value of maximum.
3. Create a 4×4 matrix using `arange` and compute `M @ M.T` using `dot()`.

In [ ]:
# ✏️ Your solution here

# Your code here...

print("Write your solution above ↑")
print("-" * 50)

# 💡 SOLUTION:
# arr = np.arange(1, 13).reshape(3, 4)
# print("Array:\n", arr)
# print("mean:", np.mean(arr), "| std:", round(np.std(arr),2),
#       "| min:", np.min(arr), "| max:", np.max(arr))
#
# x = np.linspace(0, np.pi, 100)
# y = np.sin(x)
# idx = np.argmax(y)
# print("Max sin at x =", round(x[idx], 4), "→ sin =", round(y[idx], 4))
#
# m = np.arange(1, 17).reshape(4, 4)
# print("M @ M.T:\n", np.dot(m, m.T))

Write your solution above ↑
--------------------------------------------------


---
### 🎓 Exercise 5: Mini Project — Student Grade Analyzer

You are given marks of 6 students in 5 subjects. Write NumPy code to:
1. Calculate **total and average** marks per student
2. Find the **subject-wise class average**
3. Find the **top-scoring student** overall
4. Assign **letter grades** (A: ≥80, B: 60–79, C: 40–59, F: <40)
5. **Sort students** by total marks (descending) and print the leaderboard

In [ ]:
# ✏️ Exercise 5 — Student Grade Analyzer
np.random.seed(7)

students = ['Aarav', 'Priya', 'Rohan', 'Sneha', 'Vikram', 'Kavya']
subjects = ['Maths', 'Physics', 'Chemistry', 'CS', 'English']
marks    = np.random.randint(40, 101, (6, 5))

print("Student Marks:")
print(f"{'Student':<10}", "  ".join(f"{s:>11}" for s in subjects))
print("-" * 70)
for i, s in enumerate(students):
    print(f"{s:<10}", "  ".join(f"{marks[i,j]:>11}" for j in range(5)))

print("\nYour solution below:")
print("=" * 70)

# 1. Total and average per student
# totals   = ?
# averages = ?

# 2. Subject-wise class average
# subject_avg = ?

# 3. Top-scoring student
# top_student = ?

# 4. Letter grades
# grades = np.where(...)

# 5. Sort by total (descending) and print leaderboard
# sorted_idx = ?

Student Marks:
Student          Maths      Physics    Chemistry           CS      English
----------------------------------------------------------------------
Aarav               87           44           65           94           43
Priya               59           63           79           68           97
Rohan               54           63           48           65           86
Sneha               82           66           48           79           78
Vikram              44           88           47           84           40
Kavya               51           95           98           46           59

Your solution below:


In [ ]:
# 💡 FULL SOLUTION — Exercise 5
np.random.seed(7)
students = ['Aarav', 'Priya', 'Rohan', 'Sneha', 'Vikram', 'Kavya']
subjects = ['Maths', 'Physics', 'Chemistry', 'CS', 'English']
marks    = np.random.randint(40, 101, (6, 5))

totals      = np.sum(marks, axis=1)
averages    = np.mean(marks, axis=1)
subject_avg = np.mean(marks, axis=0)
top_idx     = np.argmax(totals)
grades      = np.where(averages >= 80, 'A',
              np.where(averages >= 60, 'B',
              np.where(averages >= 40, 'C', 'F')))
sorted_idx  = np.argsort(totals)[::-1]

print("=" * 50)
print("       📊 GRADE LEADERBOARD")
print("=" * 50)
print(f"{'Rank':<5} {'Student':<10} {'Total':>6} {'Avg':>7} {'Grade':>6}")
print("-" * 38)
for rank, i in enumerate(sorted_idx, 1):
    print(f"{rank:<5} {students[i]:<10} {totals[i]:>6} {averages[i]:>7.1f} {grades[i]:>6}")

print()
print(f"🏆 Top scorer : {students[top_idx]}  ({totals[top_idx]} marks)")
print()
print("📚 Subject-wise averages:")
for s, avg in zip(subjects, subject_avg):
    print(f"   {s:<12}: {avg:.1f}")

       📊 GRADE LEADERBOARD
Rank  Student     Total     Avg  Grade
--------------------------------------
1     Priya         366    73.2      B
2     Sneha         353    70.6      B
3     Kavya         349    69.8      B
4     Aarav         333    66.6      B
5     Rohan         316    63.2      B
6     Vikram        303    60.6      B

🏆 Top scorer : Priya  (366 marks)

📚 Subject-wise averages:
   Maths       : 62.8
   Physics     : 69.8
   Chemistry   : 64.2
   CS          : 72.7
   English     : 67.2


---
## 📋 Quick Reference Summary

| Function | Description | Example |
|----------|-------------|---------|
| `np.array()` | Create array | `np.array([1,2,3])` |
| `np.zeros()` | All zeros | `np.zeros((3,4))` |
| `np.ones()` | All ones | `np.ones((2,3))` |
| `np.empty()` | Uninitialized | `np.empty((2,2))` |
| `np.eye()` | Identity matrix | `np.eye(3)` |
| `np.arange()` | Range array | `np.arange(0,10,2)` |
| `np.linspace()` | N evenly spaced | `np.linspace(0,1,5)` |
| `np.random.random()` | Random [0,1) | `np.random.random((3,3))` |
| `.reshape()` | Change shape | `arr.reshape(3,4)` |
| `np.sum()` | Sum elements | `np.sum(arr, axis=0)` |
| `np.mean()` | Average | `np.mean(arr)` |
| `np.std()` | Std deviation | `np.std(arr)` |
| `np.dot()` | Matrix product | `np.dot(A,B)` |
| `np.sort()` | Sort array | `np.sort(arr)` |
| `np.where()` | Conditional | `np.where(arr>5, arr, 0)` |
| `np.argmax()` | Index of max | `np.argmax(arr)` |
| `np.char.upper()` | Uppercase | `np.char.upper(names)` |

---
*Prepared for BTech Python Programming Course* 🎓